### ISSUE TITLE
delete button does not work when addon is enabled

### ISSUE THREAD

**Issue by salmanuc** [hafatsat-anki/Anki-Extended-deck-menu#1]
delete button does not work when addon is enabled
anki version 23.10.1

**Comment by hafatsat-anki** [comment]
Thanks for the report. I will try to make time for it as soon as possible.

**Comment by salmanuc** [comment]
i have figured out a solution with the help of chatgpt

class ask_before_delete(QDialog):
    def __init__(self, parent=mw):
        super(ask_before_delete, self).__init__(parent)
        self.setWindowTitle("Remove Deck")
        self.setWindowFlags(Qt.Dialog | Qt.MSWindowsFixedSizeDialogHint)
        self._operator = QComboBox()
        self._explanation = QLabel()
        self._explanation.setWordWrap(True)
        buttonBox = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
        buttonBox.accepted.connect(self.accept)
        buttonBox.rejected.connect(self.reject)
        layout = QGridLayout()
        layout.addWidget(QLabel('<font color=red>Are you sure you want to delete the Deck?</font>'), 6, 0, 1, 3)
        layout.addWidget(buttonBox, 8, 0, 7, 9)
        self.setLayout(layout)
        return


def open_ask_delete(did):
    ask_delete = ask_before_delete()
    if ask_delete.exec():
        aqt.operations.deck.remove_decks(parent=mw, deck_ids=[did]).run_in_background()
        
        
REPLACED it with this

def open_ask_delete(did):
    try:
        mw.col.decks.rem(did)
        
        # Trigger a deck browser reload
        mw.deckBrowser.refresh()

    except Exception as e:
        print(f"Error removing deck: {e}")


however you dont get confirmatory dialog now


ps i am not a coder

**Comment by hafatsat-anki** [comment]
Thanks for the help!
I have the knowledge to solve it, I just need to address it for an hour...
